baseURL = 'https://philtechtalks.netlify.app'
languageCode = 'en-us'
title = 'Phil.Tech.Talks'
theme = "PaperMod"
pluralizeListTitles = false
buildFuture = true

# Add this outputs section
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  mainSections = ["upcoming"]

[params.analytics.google]
  SiteVerificationTag = "G-ENE3M094RN"

# Add search customization (optional)
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
Title = "Philosophy of Technology in J√ºlich"
Content = """
Welcome to the J√ºlich Speaker Series in the Philosophy of Technology. We aim to facilitate research into ethical and philosophical questions associated with novel technologies, particularly in artificial intelligence, neuromedicine, and their intersection. The series is organized by the working group [Neuroethics and Ethics of AI](https://www.fz-juelich.de/en/inm/inm-7/research-groups/neuroethics-and-ethics-in-ai) at the [Forschungszentrum J√ºlich](https://www.fz-juelich.de/en).

&nbsp;

**Schedule change:** Starting in February, talks will be held on **Tuesdays at 10am CET** (previously Fridays).
"""

[[menu.main]]
identifier = "pasttalks"
name = "Past talks"
url = "/past_talks/"
weight = 20

[[menu.main]]
identifier = "workshop"
name = "Workshop"
url = "/workshop/"
weight = 30

[[menu.main]]
identifier = "contact"
name = "Join in"
url = "/contact/"
weight = 40

[[menu.main]]
identifier = "search"
name = "üîç"
url = "/search/"
weight = 50